# Generated by Django 4.1.7 on 2023-04-22 15:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="geekuser",
            name="age",
            field=models.SmallIntegerField(
                blank=True, null=True, verbose_name="Возраст"
            ),
        ),
    ]
